const PUPSUB_ACCOUNT = "PUPSUB_ACCOUNT";
const PUPSUB_EVENT = "PUPSUB_EVENT";
const PUPSUB_LOGIN = "PUPSUB_LOGIN";
const PUPSUB_APPLICATION = "PUPSUB_APPLICATION";
const PUPSUB_COMMENT = "PUPSUB_COMMENT";

module.exports = {
    PUPSUB_ACCOUNT,
    PUPSUB_EVENT,
    PUPSUB_LOGIN,
    PUPSUB_APPLICATION,
    PUPSUB_COMMENT
};
