const PUPSUB_ACCOUNT = "PUPSUB_ACCOUNT";
const PUPSUB_EVENT = "PUPSUB_EVENT";
const PUPSUB_LOGIN = "PUPSUB_LOGIN";
const PUPSUB_APPLICATION = "PUPSUB_APPLICATION";

module.exports = {
    PUPSUB_ACCOUNT,
    PUPSUB_EVENT,
    PUPSUB_LOGIN,
    PUPSUB_APPLICATION
};
